### ISSUE TITLE
BUG : Problem in the outer loop in J005

### ISSUE THREAD

**Issue by riddhikakundu06** [Soumyodeep-Das/learning_java#1]
In the program "**J005_loops.java**" , there is a problem i.e. for **input** :  **rows** = **n** , the program is printing **n-1** number of lines with a blank line . This issue is occurring due to bug in the condition of the inner loop i.e. there is written **j < i** , that's why when the value of **i** is **0** , the condition **j < i** fails .  Thus ,  the blank line is printed. For this problem **n - 1** number of rows are printed .

This issue can be easily solved by replacing the previous condition of the inner loop with **j <= i** . 

Kindly assign this task to me , so that I can fix this bug.

**Comment by Soumyodeep-Das** [comment]
Okay, you can do the fixes.
